### ISSUE TITLE
npm run build error: file not found

### ISSUE THREAD

**Issue by fourtrackFM** [mrkev/pkg#1]
thanks for making this, this is super useful and somewhat uncharted territory. i had been struggling with Vite and Faust not playing nicely, and was introduced to this by the maintainer of faustwasm.

so far, i see this works with `npm run dev` but not `npm run build`.

error during build (ive replaced drive paths here with ... for brevity):
```
[faust-lodaer-plugin] Could not load .../fourtrack/src/components/audio_engine/stereochorus.dsp (imported by src/components/audio_engine/audiograph.ts): ENOENT: no such file or directory, unlink '...\node_modules\@grame\faustwasm\libfaust-wasm\libfaust-wasm.mjs'
    at async Object.unlink (node:internal/fs/promises:1066:10)
    at async instantiateFaustModuleFromFile (file:///.../node_modules/@grame/faustwasm/dist/esm/index.js:63:5)
    at async faustLoaderWasmImpl (file:///.../node_modules/vite-plugin-faust/dist/vitePluginFaust.js:197:23)
    at async FaustLoader.load (file:///.../node_modules/vite-plugin-faust/dist/vitePluginFaust.js:76:19)
    at async PluginDriver.hookFirstAndGetPlugin (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:20712:28)
    at async file:///.../node_modules/rollup/dist/es/shared/node-entry.js:19832:33
    at async Queue.work (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:20922:32)
```

when  in `/synth/context.tsx`:
```
// @ts-ignore
import createAnalog from "./analog.dsp";
```
and 

```
> ls
... fourtrack\src\components\synth

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         12/3/2024   8:16 AM           3760 analog.dsp
-a----         12/3/2024   8:43 AM           8200 context.tsx
```

any idea what is going on here? thanks for any help

at first i though `noEmit: true` was the cause in my tsconfig, but still the build failed with `ENOENT: no such file`

it also looks like `libfaust-wasm.mjs` is not created here

sincerely,
anthony

**Comment by mrkev** [comment]
Hey @fourtrackFM,

The problem is here:

https://github.com/mrkev/pkg/blob/c97a26c0ae6c00022ae7ef7623fe275e02466a1a/packages/vite-plugin-faust/FaustLoader.ts#L254-L257

I get

**Comment by mrkev** [comment]
Hey @fourtrackFM,

The problem is here:

https://github.com/mrkev/pkg/blob/c97a26c0ae6c00022ae7ef7623fe275e02466a1a/packages/vite-plugin-faust/FaustLoader.ts#L254-L257

I get `FAUST_MODULE_PATH` via `require.resolve`:

https://github.com/mrkev/pkg/blob/c97a26c0ae6c00022ae7ef7623fe275e02466a1a/packages/vite-plugin-faust/FaustLoader.ts#L15-L18

Could you share with me:

- what version of node are you using (or bun, deno, etc if you're using one of those)
- wether the `package.json` for this project has a `"type": "module"` entry

Like the error notes, `...\node_modules\@grame\faustwasm\libfaust-wasm\libfaust-wasm.mjs` does not exist, but `...\node_modules\@grame\faustwasm\libfaust-wasm\libfaust-wasm.js` does.  That `require.resolve` above should resolve to the `.js` file, and I'm wondering why it's assuming it should be a `.mjs` file instead.
